# Generated by Django 4.2.3 on 2023-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
